---
application:
  name: "wordpress"
  project: "zuri-news-wordpress"
  organization: "QoveryCommunity"
  storage:
  - name: "content"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/content"
databases:
- type: "MYSQL"
  name: "zuri"
  version: "8.0"
routers:
- name: "main-wordpress"
  routes:
  - application_name: "wordpress"
    paths:
    - "/*"
